### ISSUE TITLE
Re-open Banner when add new script

### ISSUE THREAD

**Issue by venumdev** [OFFLINE-GmbH/oc-gdpr-plugin#32]
Hi to all,
how do I re-open the banner to those who have already accepted the coockie previously once new scripts have been implemented?

**Comment by tobias-kuendig** [comment]
Good question, @ayumihamsaki do you know what to do in this case? If a user adds new scripts via the backend should the banner reappear again?

**Comment by damsfx** [comment]
@tobias-kuendig ,  according to Recital [#32](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=OJ:L:2016:119:FULL&from=EN) : 

> Consent should be given by a clear affirmative act establishing a **freely given, specific, informed and unambiguous** indication of the data subject's agreement to the processing of personal data relating to him or her ....
>  Consent should cover all processing activities carried out for the same purpose or purposes. When the processing has multiple purposes, consent should be given **for all of them** .

With that say, I think if the list of scripts/cookies change, the banner has to be visible again in order to get the explicit consent for all services.

If you are more confortable with German language see : [Official Journal of the European Union side by side EN/DE ](https://eur-lex.europa.eu/legal-content/EN-DE/TXT/?uri=CELEX:32016R0679&from=EN)

**Comment by ayumihamsaki** [comment]
@venumdev Hi, I spoke about this in issue: https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/issues/23

Your question would be under the "**Show**" 

You have two choices:

1. To re-open the banner.
2. Or Link to the Advanced Settings Page.

I would recommend just adding a link in the footer saying: 

`<a href="https://www.example.com/privacy-and-cookie-policy">Update Consent</a>`

Info about this can also be found inside the cookie plugin (I added it yesterday) found by navigating to:

OctoberCMS Back-End > Settings > GDPR and ePrivacy (Tab) > Info and Help > Information about GDPR and ePrivacy > Table of Contents (Section 23 - Show)

If however you are totally set on re-showing the Banner please comment below and we will add this feature.

(The reason for linking in the footer is that banners and pop-ups are annoying and also legally and good user experience its best to link to the advanced settings page for all the options. So that is why it would be best to only show the banner once - if the user clicked on dismiss, accept or reject).

I did write and explain all that and more in the info section.

Anyway, let us know if I didn't answer your question?

**Comment by ayumihamsaki** [comment]
Cool updated the Plugin Info Section see Screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/41869755-e83127aa-78b1-11e8-82a7-8aeed25700a6.png)

~Will do a Pull Request on it now.

**Comment by ayumihamsaki** [comment]
Reserved gonna add an extra comment here in a bit.

**Comment by ayumihamsaki** [comment]
I just thought, you should also "**date the policy**" if you do any changes and maybe also _archive them_, I have do a second Pull Request to add that extra info as well, see screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/41871934-48752606-78b8-11e8-8950-846bda184443.png)

**Comment by ayumihamsaki** [comment]
@tobias-kuendig What do you think about adding a feature to let webmaster "archive" old config setups and be able to display them on the front end?

**Comment by venumdev** [comment]
It would not be better to generate a cookie that keeps track of the saved version. If the version is different, have the banner reopen?

**Comment by tobias-kuendig** [comment]
I guess if it's not neccessary to show the banner a second time we really shouldn't do it since this is distracting to the user.

**Comment by ayumihamsaki** [comment]
> It would not be better to generate a cookie that keeps track of the saved version. If the version is different, have the banner reopen?

I think I understand what you are saying, GDPR has a section about storing and keeping records, if a User requests their infomation from your website you have to give them all the data within a certain time frame on that User. So you would need to store the info as a "Hard-Copy" in the backend. So you couldn't save it as a cookie. The versions would have to be a physical hard-copy.

This is an argument I am having with many people, because that data should be encrpyted to prevent security hacking! And needs to be stored in an organized structure for organizations and businesses to produce it to the User "**On Request**".

~ Hope I make sense, what I'm trying to say.

Maybe this video will help you understand a bit more: https://www.youtube.com/watch?v=WPwG-MNMuBQ

**Comment by tobias-kuendig** [comment]
Since it is sufficient by the law and better UX we won't include an option to re-show the banner again if the cookies have changed. Make sure to place the settings link into your footer so users can update their consent at any time.
