### ISSUE TITLE
Settings of group and module are not accepted

### ISSUE THREAD

**Issue by RonMen** [OFFLINE-GmbH/oc-gdpr-plugin#61]
Hi.

We use a setting for group that is not activated to be required for the website to function and work but we have a cookie/module that should be initialy activated, but it isn't. Is there an issue with the implementation?

Regards
RonMen

**Comment by tobias-kuendig** [comment]
All cookies managed through the GDPR plugin are not set as long as the user has not accepted the cookies.

Marking a group as required makes it so that the user cannot disable this group in the cookie manager. The cookies themselves, however, are still not set without the user's consent.

Marking a cookie as «turned on at start-up» only makes this cookie accepted by default, once the user accepted the cookies. Setting this option to false will not set the cookie unless the user specifically enables it using the cookie manager.

**Comment by RonMen** [comment]
Thank @tobias-kuendig for your statement.

> Marking a cookie as «turned on at start-up» only makes this cookie accepted by default, once the user accepted the cookies. Setting this option to false will not set the cookie unless the user specifically enables it using the cookie manager.

Like you wrote we set up a cookie to «turned on at start-up», but it isn't activated by default, also not event the user accepted the cookies. It always stays grey/deactivated.

Regards
RonMen
