### ISSUE TITLE
Twig partial import: Fileextension js is invalid

### ISSUE THREAD

**Issue by TimFoerster** [OFFLINE-GmbH/oc-gdpr-plugin#77]
Looks like Build > 1.0.469 does not allow imports of js files anymore. 

Changing from `.js` to `.js.htm`  would fix the issue, but breaks existing custom `config.js` and `app.js` 

See also here: https://github.com/skydiver/october-plugin-forms/issues/213

**Comment by tobias-kuendig** [comment]
The Klaro! consent manager is no longer officially supported by this plugin. It is still stere for compatibilty reasons but we actually suggest to use the built in cookie banner/manager.

For anyone that has this issue, the fix is rather easy: Just override the component partials to use `.htm` extensions as @TimFoerster suggested.

As this component is no longer supported, I wouldn't be afraid of future breaking updates as we probably won't update the partials. Also, the partials are rather small and can live in your theme without a problem.
