### ISSUE TITLE
Install from backend throws error: A package name was not specified

### ISSUE THREAD

**Issue by HeinCorbet** [OFFLINE-GmbH/oc-gdpr-plugin#79]
Using the 'install plugin' from the backend (october cms build 472) throws error in pop-up 'A package name was not specified'
Using the default provided does not work. Plugin will not install.

![image](https://user-images.githubusercontent.com/14921720/115004614-43d9b400-9ea7-11eb-9c89-d780ea398147.png)

Could it be because the 'public function pluginDetails()' is missing in the Plugin.php ?

**Comment by tobias-kuendig** [comment]
> Could it be because the 'public function pluginDetails()' is missing in the Plugin.php ?

This info is in https://github.com/OFFLINE-GmbH/oc-gdpr-plugin/blob/develop/plugin.yaml

It might be because of the October v2 release. I'll try to reproduce this next week and see if the problem was only temporary.

You can use `composer require offline/oc-gdpr-plugin` in the meantime to install the plugin (or simply copy the plugins/offline/gdpr folder over from another installation.

**Comment by tobias-kuendig** [comment]
I cannot reproduce this issue on the latest October release. Please let me know if you still experience the problem.
